on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        BUILD_DIR: notes
        BUILD_THEMES: false # wtf.. Maybe it will work next time?
        PAGES_BRANCH: gh-pages
        TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}